# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: eliasonic
# "service" is the name of this project. This will also be added to your AWS resource names.
service: online-shopping-monolithic

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 10
  stage: dev

functions:
  shopping-app:
    handler: src/lambda.handler
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      APP_SECRET: jg_youtube_tutorial
      #MONGODB_URI: 